### ISSUE TITLE
any plan on using/reusing websockets and nats

### ISSUE THREAD

**Issue by SunChero** [nakamauwu/nakama#64]
this is certainly not an issue but more of question/suggestion.
first of all thank for great work and youtube videos .. this old and new/ongoing series .. really much appreciated

my question is related to the use of NATS and webscocket for some real time interaction... 

thanks again

**Comment by nicolasparada** [comment]
Thanks for the interest.
Yes, the plan is to add realtime capabilities to the application so there is no need to reload pages.
Probably it will use the same tech. Some SSE endpoints backed by NATS 👍
