### ISSUE TITLE
[Feature Request] Default home filter

### ISSUE THREAD

**Issue by jesuscc1993** [nakamauwu/nakama#65]
_Current state:_

App always loads the "global" filter by default.
User can change to "following", but "global" will be loaded again on the next load.
The URL doesn't change either, so we can't bookmark the desired filter either.

_Suggestion:_

App should remember and load the latest use filter.
Alternatively, as a bare minimum, it should be a URL param so we can bookmark the desired filter.

**Comment by nicolasparada** [comment]
Agree.

**Comment by nicolasparada** [comment]
Done
