### ISSUE TITLE
Generalized DB package to use drivers for CockroachDB, PostgreSQL, and MariaDB/MySQL.

### ISSUE THREAD

**Issue by thomastthai** [nakamauwu/nakama#81]

**Comment by nicolasparada** [comment]
This is something I wanted to do from the start... But I don't know if I want it anymore.
Even tho all those databases use SQL, they offer different features. And having a generic database layer that work with all of them would prevent us from taking full advantage.

**Comment by thomastthai** [comment]
There is that trade-off with abstracting DB connections. If a choice had to be made with which DB to choose, I'd recommend PostgreSQL. With the addition of AGE, a graph extension, Postgresql offers both SQL and graph. Graph capabilities would help add future features or make the calculation of social connections faster.
