### ISSUE TITLE
Postings from Following Not Showing on Timeline

### ISSUE THREAD

**Issue by thomastthai** [nakamauwu/nakama#96]
In the `Timeline`, `Global` works fine. However, when clicking on `Following`, the postings from people I'm following aren't showing up. I tested this on my local install using the `next` branch. It could be that it's behind by some months. [nakama.social](https://nakama.social/) seems to display the `Timeline` for `Following` just fine.

P.S. sorry I've not been back on this project in about a year!

**Comment by nicolasparada** [comment]
Shall I close this then?

PS: thanks for checking this out ;)
